// app/components/upload/PdfUploader.vue
<template>
  <div class="w-full max-w-3xl mx-auto">
    <!-- PDF drop zone (múltiplos arquivos) -->
    <div
      class="relative flex flex-col items-center justify-center gap-3 rounded-3xl border-2 border-dashed px-8 py-12 text-center transition-colors duration-200 cursor-pointer"
      :class="isDragging
        ? 'border-blue-500 bg-blue-500/10'
        : 'border-slate-300 bg-white/5 hover:border-blue-400 hover:bg-blue-500/5'"
      @dragenter.prevent="isDragging = true"
      @dragover.prevent="isDragging = true"
      @dragleave.prevent="isDragging = false"
      @drop.prevent="onDrop"
      @click="openFilePicker"
    >
      <Icon
        name="lucide:file-up"
        class="mb-1 h-12 w-12 text-slate-400"
      />
      <p class="text-sm font-semibold text-slate-200">
        Arraste e solte aqui os PDFs das suas faturas
      </p>
      <p class="text-xs text-slate-400">
        ou clique para selecionar — vários arquivos permitidos (máx. 20MB cada)
      </p>
      <input
        ref="fileInput"
        type="file"
        accept="application/pdf"
        multiple
        class="hidden"
        @change="onFileSelected"
      >
    </div>

    <p
      v-if="errorMessage"
      role="alert"
      class="mt-4 rounded-xl bg-red-500/10 px-4 py-3 text-sm text-red-400"
    >{{ errorMessage }}</p>

    <!-- Fila (apple-design: interface única do lote — item ativo expande, wayfinding total) -->
    <div v-if="queue.length > 0" class="mt-5 flex flex-col gap-2" aria-label="Fila de importação">
      <!-- P3: header macro do lote -->
      <div class="flex items-center justify-between px-1">
        <p class="text-xs font-extrabold text-muted">
          Importando <span class="text-highlighted">{{ doneCount + (activeId ? 1 : 0) }}</span> de {{ queue.length }}
        </p>
        <span
          v-if="doneCount === queue.length"
          class="inline-flex items-center gap-1.5 rounded-lg bg-emerald-500/15 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wider text-emerald-600 dark:text-emerald-400"
        >
          <Icon name="lucide:check" class="h-3 w-3" /> Lote concluído
        </span>
      </div>

      <AnimatePresence>
        <motion.div
          v-for="(item, idx) in queue"
          :key="item.id"
          class="overflow-hidden rounded-2xl glass-card"
          :initial="{ opacity: 0, y: 8 }"
          :animate="{ opacity: 1, y: 0 }"
          :exit="{ opacity: 0, transform: 'translateX(-12px)' }"
          :transition="{ duration: 0.25, ease: EASE_OUT_UI, delay: Math.min(idx * 0.04, 0.2) }"
        >
          <!-- Row: sempre visível (compacto) -->
          <div
            class="flex items-center gap-3 px-4 py-3"
            :class="item.id === activeId ? 'border-l-2 border-brand-500' : ''"
          >
            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-brand-500/10 text-brand-500">
              <Icon
                v-if="item.status === 'parsing'"
                name="lucide:loader-2"
                class="h-4.5 w-4.5 animate-spin"
              />
              <Icon
                v-else
                :name="item.status === 'done' ? 'lucide:check' : item.status === 'error' ? 'lucide:alert-circle' : 'lucide:file-text'"
                class="h-4.5 w-4.5"
                :class="item.status === 'done' ? 'text-emerald-500' : item.status === 'error' ? 'text-red-500' : ''"
              />
            </div>
            <div class="min-w-0 flex-1">
              <p class="truncate text-xs font-extrabold text-highlighted">{{ item.name }}</p>
              <p class="text-[10px] text-muted">
                {{ statusLabel(item.status) }} · {{ formatBytes(item.size) }}
                <template v-if="item.id === activeId"> · {{ activeStageLabel }}</template>
              </p>
            </div>
            <span
              class="inline-flex items-center rounded-lg px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wider"
              :class="statusChipClass(item.status)"
            >
              {{ statusLabel(item.status) }}
            </span>
            <button
              v-if="item.status === 'pending' || item.status === 'error' || item.status === 'done'"
              type="button"
              aria-label="Remover da fila"
              class="rounded-lg p-1 text-dimmed hover:bg-red-500/10 hover:text-red-500 transition-colors cursor-pointer"
              @click="onRemoveItem(item.id)"
            >
              <Icon name="lucide:x" class="h-3.5 w-3.5" />
            </button>
          </div>

          <!-- P1: item ativo expande — etapa IA + barra, no próprio item (sem overlay) -->
          <motion.div
            v-if="item.id === activeId"
            class="flex items-center gap-3 border-t border-default/60 bg-brand-500/[0.06] px-4 py-3"
            :initial="{ opacity: 0, height: 0 }"
            :animate="{ opacity: 1, height: 'auto' }"
            :exit="{ opacity: 0, height: 0 }"
            :transition="{ duration: 0.25, ease: [0.23, 1, 0.32, 1] }"
          >
            <p class="min-w-0 flex-1 text-xs font-bold text-default">
              <Icon name="lucide:sparkles" class="mr-1.5 inline h-3.5 w-3.5 text-brand-500" />
              {{ activeStageLabel }}
            </p>
            <div class="h-1.5 w-28 overflow-hidden rounded-full bg-current/10">
              <div class="h-full w-1/3 animate-pulse rounded-full bg-brand-500" />
            </div>
          </motion.div>

          <!-- Erro do item -->
          <div
            v-if="item.status === 'error' && item.error"
            class="border-t border-default/60 px-4 py-2.5 text-[11px] font-bold text-red-500"
          >
            {{ item.error }}
          </div>
        </motion.div>
      </AnimatePresence>
    </div>

    <!-- Password prompt modal -->
    <UiAppModal
      :open="showPasswordModal"
      title="Fatura protegida por senha"
      :closable="false"
    >
      <form
        class="flex flex-col gap-4"
        @submit.prevent="onPasswordSubmit"
      >
        <p class="text-sm text-slate-300">
          {{ activeItemName ? `O arquivo ${activeItemName} está` : 'Este PDF está' }} cifrado. Insira a senha (ex: CPF ou data de nascimento).
        </p>
        <UiAppInput
          v-model="passwordInput"
          label="Senha do PDF"
          :type="showPasswordText ? 'text' : 'password'"
        />
        <div class="flex items-center justify-between gap-3">
          <button
            type="button"
            class="text-xs font-medium text-slate-400 hover:text-slate-200 cursor-pointer"
            @click="showPasswordText = !showPasswordText"
          >
            {{ showPasswordText ? 'Ocultar senha' : 'Mostrar senha' }}
          </button>
          <div class="flex items-center gap-2">
            <UiAppButton
              variant="ghost"
              @click="onCancelPassword"
            >Cancelar</UiAppButton>
            <UiAppButton
              type="submit"
              :disabled="loading"
            >{{ loading ? 'Verificando…' : 'Desbloquear' }}</UiAppButton>
          </div>
        </div>
      </form>
    </UiAppModal>

    <UiAppToast
      :open="toastOpen"
      :message="toastMessage"
      :tone="toastTone"
      @close="toastOpen = false"
    />
  </div>
</template>

<script setup lang="ts">
import { motion, AnimatePresence } from 'motion-v'
import { EASE_OUT_UI } from '~/utils/motion'
import { useUploadQueue, type QueueItemStatus } from '~/composables/useUploadQueue'
import type { ParseResponse } from '~/types/ParseResponse'
import { useParse } from '~/composables/useParse'

/**
 * PDF uploader com fila sequencial: múltiplos arquivos, processados 1 a 1.
 * apple-design: a FILA é a única interface — item ativo expande com a etapa
 * da IA, sem overlay fullscreen que esconda o todo (wayfinding).
 */

const emit = defineEmits<{
  'invoice-parsed': [response: ParseResponse, file: File]
  'review-meta': [meta: { fileName: string; index: number; total: number }]
}>()

const { parseInvoice } = useParse()
const {
  queue, activeId, awaitingReview,
  addFiles, removeItem, nextPending, startItem, markNeedsPassword, finishItem, failItem,
} = useUploadQueue()

const isDragging = ref(false)
const loading = ref(false)
const errorMessage = ref<string | null>(null)
const showPasswordModal = ref(false)
const passwordInput = ref('')
const showPasswordText = ref(false)
const fileInput = ref<HTMLInputElement | null>(null)

const doneCount = computed(() => queue.value.filter((i) => i.status === 'done').length)

const activeStageLabel = computed(() => {
  if (loading.value) return 'Extraindo dados com IA (Gemini → contingência)…'
  return 'Preparando…'
})

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function statusLabel(status: QueueItemStatus): string {
  switch (status) {
    case 'pending': return 'Na fila'
    case 'parsing': return 'Processando'
    case 'needs_password': return 'Senha'
    case 'done': return 'Importado'
    case 'error': return 'Erro'
    default: return status
  }
}

function statusChipClass(status: QueueItemStatus): string {
  switch (status) {
    case 'parsing': return 'bg-brand-500/15 text-brand-600 dark:text-brand-400'
    case 'needs_password': return 'bg-amber-500/15 text-amber-600 dark:text-amber-400'
    case 'done': return 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400'
    case 'error': return 'bg-red-500/15 text-red-600 dark:text-red-400'
    default: return 'bg-slate-500/15 text-muted'
  }
}

// ===== Fila =====

function enqueueFiles(files: FileList | File[]) {
  const items = addFiles(files)
  const invalid = items.filter((i) => i.status === 'error').length
  if (invalid > 0) {
    showToast(`${invalid} arquivo(s) ignorado(s): só PDF é aceito.`, 'error')
  }
  if (!loading.value && !awaitingReview.value) {
    void processNext()
  }
}

async function processNext(): Promise<void> {
  const item = nextPending()
  if (!item) {
    loading.value = false
    return
  }
  startItem(item)
  await processFile(item.file)
}

function onRemoveItem(id: string) {
  removeItem(id)
}

/** ImportFlow chama após save p/ retomar a fila */
function resumeQueue() {
  awaitingReview.value = false
  if (!loading.value) void processNext()
}

function hasPending(): boolean {
  return queue.value.some((i) => i.status === 'pending')
}

defineExpose({ resumeQueue, hasPending })

// ===== Processar (1 arquivo) =====
async function processFile(file: File, password?: string) {
  loading.value = true
  errorMessage.value = null

  try {
    const response = await parseInvoice(file, password)

    if (response.requiresPassword) {
      markNeedsPassword()
      showPasswordModal.value = true
      if (password) {
        errorMessage.value = 'Senha incorreta. Verifique e tente novamente (ex: CPF ou Data de Nascimento).'
      }
      loading.value = false
      return
    }

    const item = finishItem(response)
    // P2: meta p/ o modal de revisão (nome + posição no lote)
    emit('review-meta', {
      fileName: item?.name ?? file.name,
      index: doneCount.value,
      total: queue.value.length,
    })
    loading.value = false
    // Pausa a fila: modal de revisão assume; retoma em resumeQueue() pós-save
    emit('invoice-parsed', response, file)
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Erro inesperado ao ler a fatura PDF.'
    errorMessage.value = msg
    if (activeId.value) failItem(activeId.value, msg)
    loading.value = false
  }
}

// ===== Entradas =====
function onFileSelected(event: Event) {
  const input = event.target as HTMLInputElement
  if (input.files && input.files.length > 0) {
    enqueueFiles(input.files)
  }
  input.value = ''
}

function onDrop(event: DragEvent) {
  isDragging.value = false
  if (event.dataTransfer?.files?.length) {
    enqueueFiles(event.dataTransfer.files)
  }
}

function openFilePicker() {
  fileInput.value?.click()
}

// ===== Senha (do item ativo) =====
function onPasswordSubmit() {
  const item = queue.value.find((i) => i.status === 'needs_password')
  if (!item) return
  if (!passwordInput.value.trim()) {
    errorMessage.value = 'Digite a senha da fatura.'
    return
  }
  showPasswordModal.value = false
  void processFile(item.file, passwordInput.value)
}

function onCancelPassword() {
  showPasswordModal.value = false
  passwordInput.value = ''
  loading.value = false
  if (activeId.value) failItem(activeId.value, 'Senha cancelada.')
}

// ===== Toast interno (arquivo inválido) =====
const toastOpen = ref(false)
const toastMessage = ref('')
const toastTone = ref<'success' | 'error' | 'info'>('info')
let toastTimer: ReturnType<typeof setTimeout> | null = null

function showToast(msg: string, tone: 'success' | 'error' | 'info' = 'info') {
  toastMessage.value = msg
  toastTone.value = tone
  toastOpen.value = true
  if (toastTimer) clearTimeout(toastTimer)
  toastTimer = setTimeout(() => { toastOpen.value = false }, 4000)
}
</script>

// src/components/PdfUploader.tsx
import React, { useState, useRef } from 'react';
import {
  UploadCloud,
  Lock,
  FileSearch,
  Building2,
  Cpu,
  Calculator,
  CheckCircle2,
  Loader2,
  Eye,
  EyeOff,
  KeyRound,
  AlertCircle,
  FileText,
  Sparkles,
} from 'lucide-react';
import { ParseResponse } from '../types/index.js';

interface PdfUploaderProps {
  apiKey?: string;
  onInvoiceParsed: (response: ParseResponse, file: File) => void;
}

interface ImportStage {
  id: number;
  title: string;
  description: string;
  icon: React.ElementType;
}

const IMPORT_STAGES: ImportStage[] = [
  {
    id: 1,
    title: 'Lendo Arquivo e Verificando Criptografia',
    description: 'Carregando documento PDF e conferindo chaves salvas...',
    icon: FileSearch,
  },
  {
    id: 2,
    title: 'Solicitando Extração por IA (Tentativas 1 a 3)',
    description: 'Enviando fatura para análise inteligente de compras e parcelas...',
    icon: Sparkles,
  },
  {
    id: 3,
    title: 'Mapeando Banco e Cartões',
    description: 'Agrupando lançamentos por cartão (ex: Mercado Pago, Nubank, Itaú)...',
    icon: Building2,
  },
  {
    id: 4,
    title: 'Validação Matemática dos Totais',
    description: 'Conferindo a soma das compras contra o valor total do boleto...',
    icon: Calculator,
  },
  {
    id: 5,
    title: 'Fallback Determinístico Local',
    description: 'Verificando extratores locais de contingência se necessário...',
    icon: Cpu,
  },
  {
    id: 6,
    title: 'Conferência Concluída com Sucesso',
    description: 'Preparando lançamentos extraídos para revisão final...',
    icon: CheckCircle2,
  },
];

export const PdfUploader: React.FC<PdfUploaderProps> = ({ apiKey, onInvoiceParsed }) => {
  const [isDragging, setIsDragging] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Estados do Preloader por Etapas
  const [currentStageId, setCurrentStageId] = useState(1);
  const [progressPercent, setProgressPercent] = useState(8);

  // Estados para PDF protegido por senha
  const [currentFile, setCurrentFile] = useState<File | null>(null);
  const [showPasswordModal, setShowPasswordModal] = useState(false);
  const [passwordInput, setPasswordInput] = useState('');
  const [showPasswordText, setShowPasswordText] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  const startPreloadSimulation = () => {
    setCurrentStageId(1);
    setProgressPercent(8);

    if (timerRef.current) clearInterval(timerRef.current);

    timerRef.current = setInterval(() => {
      setProgressPercent((prev) => {
        if (prev >= 92) {
          return 92; // Pausa no 92% até a resposta do backend
        }
        const next = prev + Math.floor(Math.random() * 5) + 3;
        if (next >= 18 && next < 38) setCurrentStageId(2);
        else if (next >= 38 && next < 58) setCurrentStageId(3);
        else if (next >= 58 && next < 78) setCurrentStageId(4);
        else if (next >= 78 && next < 92) setCurrentStageId(5);
        return next;
      });
    }, 380);
  };

  const stopPreloadSimulation = () => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
  };

  const processFile = async (file: File, password?: string) => {
    if (!file || file.type !== 'application/pdf') {
      setErrorMessage('Por favor, selecione um arquivo no formato PDF.');
      return;
    }

    setLoading(true);
    setErrorMessage(null);
    setCurrentFile(file);
    startPreloadSimulation();

    try {
      const formData = new FormData();
      formData.append('file', file);
      if (apiKey) {
        formData.append('apiKey', apiKey);
      }
      if (password) {
        formData.append('password', password);
      }

      const res = await fetch('/api/parse-invoice', {
        method: 'POST',
        body: formData,
      });

      const json = await res.json();

      stopPreloadSimulation();

      // Caso o backend solicite a senha do PDF
      if (json.requiresPassword) {
        setShowPasswordModal(true);
        if (password) {
          setErrorMessage('Senha incorreta. Verifique e tente novamente (ex: CPF ou Data de Nascimento).');
        }
        setLoading(false);
        return;
      }

      if (!res.ok || !json.success) {
        throw new Error(json.error || 'Falha ao processar a fatura PDF.');
      }

      // Concluir no 100% (Etapa 6)
      setCurrentStageId(6);
      setProgressPercent(100);

      setTimeout(() => {
        setShowPasswordModal(false);
        setPasswordInput('');
        setLoading(false);
        onInvoiceParsed(json, file);
      }, 400);
    } catch (err: any) {
      stopPreloadSimulation();
      console.error(err);
      setErrorMessage(err.message || 'Erro inesperado ao ler a fatura PDF.');
      setLoading(false);
    }
  };

  const handlePasswordSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!currentFile) return;
    if (!passwordInput.trim()) {
      setErrorMessage('Digite a senha da fatura.');
      return;
    }
    processFile(currentFile, passwordInput);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  return (
    <div className="w-full max-w-3xl mx-auto">
      {/* Área de Drop de Arquivo PDF */}
      <div
        onDragOver={(e) => {
          e.preventDefault();
          setIsDragging(true);
        }}
        onDragLeave={() => setIsDragging(false)}
        onDrop={handleDrop}
        onClick={() => !loading && fileInputRef.current?.click()}
        className={`relative cursor-pointer rounded-3xl p-10 text-center transition-all duration-300 glass-card border-2 border-dashed ${
          isDragging
            ? 'border-blue-500 bg-blue-50 scale-[1.01]'
            : 'border-slate-200 hover:border-blue-400 hover:bg-slate-50'
        }`}
      >
        <input
          type="file"
          ref={fileInputRef}
          onChange={(e) => e.target.files && e.target.files.length > 0 && processFile(e.target.files[0])}
          accept="application/pdf"
          className="hidden"
        />

        <div className="flex flex-col items-center justify-center">
          <div className="w-16 h-16 rounded-2xl bg-blue-50 border border-blue-100 text-blue-600 flex items-center justify-center mb-4 glow-blue">
            <UploadCloud className="w-8 h-8" />
          </div>

          <h3 className="text-xl font-extrabold text-slate-900 mb-2">
            Arraste sua fatura PDF aqui ou clique para buscar
          </h3>

          <p className="text-xs text-slate-500 max-w-md mb-4 leading-relaxed">
            Suporta faturas em PDF de qualquer banco (inclusive faturas protegidas por senha).
          </p>

          <div className="flex items-center gap-2 px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-500">
            <Lock className="w-3.5 h-3.5 text-amber-500" />
            <span>Suporte automático para PDFs protegidos por senha</span>
          </div>
        </div>
      </div>

      {errorMessage && !showPasswordModal && !loading && (
        <div className="mt-4 p-4 rounded-2xl bg-red-50 border border-red-200 text-red-600 flex items-center gap-3 text-sm">
          <AlertCircle className="w-5 h-5 shrink-0" />
          <span>{errorMessage}</span>
        </div>
      )}

      {/* Modal de Preloader por Etapas */}
      {loading && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm font-sans">
          <div className="w-full max-w-lg glass-modal rounded-3xl p-6 sm:p-8 border border-blue-100 shadow-xl space-y-6">
            {/* Cabeçalho do Preloader */}
            <div className="flex items-center justify-between border-b border-slate-100 pb-4">
              <div className="flex items-center gap-3">
                <div className="p-3 bg-blue-50 border border-blue-100 rounded-2xl text-blue-600 glow-blue">
                  <Sparkles className="w-6 h-6 animate-pulse" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-slate-900 tracking-tight flex items-center gap-2">
                    Importando Fatura PDF
                  </h3>
                  <p className="text-xs text-slate-500 flex items-center gap-1.5 mt-0.5 font-mono">
                    <FileText className="w-3.5 h-3.5 text-blue-600" />
                    <span className="truncate max-w-[220px]">{currentFile?.name || 'documento.pdf'}</span>
                    <span>• {currentFile ? (currentFile.size / 1024).toFixed(0) : '0'} KB</span>
                  </p>
                </div>
              </div>
              <div className="text-right font-mono font-bold text-blue-600 text-lg">
                {progressPercent}%
              </div>
            </div>

            {/* Barra de Progresso Animada com Gradiente */}
            <div className="space-y-1.5">
              <div className="w-full bg-slate-100 rounded-full h-3 p-0.5 border border-slate-200 overflow-hidden">
                <div
                  className="bg-gradient-to-r from-blue-600 via-indigo-500 to-cyan-400 h-full rounded-full transition-all duration-300 shadow-sm"
                  style={{ width: `${progressPercent}%` }}
                />
              </div>
              <div className="flex justify-between text-[11px] font-mono text-slate-500">
                <span>Processando leitura</span>
                <span>Etapa {currentStageId} de {IMPORT_STAGES.length}</span>
              </div>
            </div>

            {/* Lista das Etapas com Indicador Ativo */}
            <div className="space-y-3 pt-1">
              {IMPORT_STAGES.map((stage) => {
                const IconComponent = stage.icon;
                const isDone = stage.id < currentStageId;
                const isCurrent = stage.id === currentStageId;
                const isPending = stage.id > currentStageId;

                return (
                  <div
                    key={stage.id}
                    className={`flex items-start gap-3.5 p-3 rounded-2xl border transition-all duration-300 ${
                      isCurrent
                        ? 'bg-blue-50 border-blue-200 text-slate-900 scale-[1.01] shadow-sm'
                        : isDone
                        ? 'bg-slate-50 border-slate-200 text-slate-600 opacity-90'
                        : 'bg-white border-slate-100 text-slate-400 opacity-40'
                    }`}
                  >
                    <div
                      className={`p-2 rounded-xl border shrink-0 mt-0.5 ${
                        isCurrent
                          ? 'bg-blue-100 border-blue-200 text-blue-600'
                          : isDone
                          ? 'bg-emerald-50 border-emerald-200 text-emerald-600'
                          : 'bg-slate-50 border-slate-200 text-slate-400'
                      }`}
                    >
                      {isDone ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                      ) : isCurrent ? (
                        <Loader2 className="w-4 h-4 text-blue-600 animate-spin" />
                      ) : (
                        <IconComponent className="w-4 h-4" />
                      )}
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between">
                        <h4
                          className={`text-xs font-bold ${
                            isCurrent ? 'text-blue-700' : isDone ? 'text-slate-700' : 'text-slate-400'
                          }`}
                        >
                          {stage.title}
                        </h4>
                        {isCurrent && (
                          <span className="text-[10px] font-mono font-semibold uppercase px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 border border-blue-200 animate-pulse">
                            Em Andamento
                          </span>
                        )}
                      </div>
                      <p
                        className={`text-[11px] mt-0.5 leading-snug ${
                          isCurrent ? 'text-slate-600' : 'text-slate-500'
                        }`}
                      >
                        {stage.description}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* Modal de Solicitação de Senha do PDF */}
      {showPasswordModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm">
          <div className="w-full max-w-md glass-modal rounded-3xl p-6 sm:p-8 border border-amber-100 shadow-xl">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-3 bg-amber-50 rounded-2xl border border-amber-100 text-amber-600">
                <KeyRound className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-slate-900">Fatura Protegida por Senha</h3>
                <p className="text-xs text-slate-500">{currentFile?.name}</p>
              </div>
            </div>

            <p className="text-xs text-slate-600 mb-4 leading-relaxed">
              Esta fatura PDF exige uma senha para ser aberta. Geralmente os bancos utilizam os primeiros dígitos do seu <strong className="text-slate-900">CPF</strong> ou sua <strong className="text-slate-900">Data de Nascimento (DDMMAAAA)</strong>.
            </p>

            <form onSubmit={handlePasswordSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-medium text-slate-500 mb-1.5">Senha da Fatura PDF</label>
                <div className="relative">
                  <input
                    type={showPasswordText ? 'text' : 'password'}
                    value={passwordInput}
                    onChange={(e) => setPasswordInput(e.target.value)}
                    placeholder="Digite a senha do PDF..."
                    autoFocus
                    className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl text-slate-900 placeholder-slate-400 focus:outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100 text-sm font-mono"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPasswordText(!showPasswordText)}
                    className="absolute right-3 top-3 text-slate-400 hover:text-slate-600 cursor-pointer"
                  >
                    {showPasswordText ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>
              </div>

              {errorMessage && (
                <div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-600 text-xs flex items-center gap-2">
                  <AlertCircle className="w-4 h-4 shrink-0" />
                  <span>{errorMessage}</span>
                </div>
              )}

              <div className="flex items-center justify-end gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => {
                    setShowPasswordModal(false);
                    setErrorMessage(null);
                    setPasswordInput('');
                  }}
                  className="px-4 py-2.5 text-xs font-semibold text-slate-500 hover:text-slate-900 rounded-xl transition-colors cursor-pointer"
                >
                  Cancelar
                </button>

                <button
                  type="submit"
                  disabled={loading}
                  className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-500 hover:to-orange-500 text-white text-xs font-extrabold rounded-xl transition-colors duration-200 shadow-sm cursor-pointer disabled:opacity-50"
                >
                  {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Lock className="w-4 h-4" />}
                  Desbloquear e Continuar
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
